name: Lint and Test

on:
  push:
  pull_request:

jobs:
  lint-test:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: "1.4"

      - name: Install dependencies
        run: poetry install

      - name: Run flake8
        run: "poetry run flake8 \
          --format='::error file=%(path)s,line=%(row)d,col=%(col)d::\
          [flake8] %(code)s: %(text)s'"

      - name: Run tests
        run: "poetry run pytest"

